### ISSUE TITLE
Adding `biocViews:` to DESCRIPTION

### ISSUE THREAD

**Issue by Ax3man** [StaThin/ggm#3]
Dear prof. Marchetti,

My package `phylopath` depends on your very useful `ggm` package. An issue that sometimes occurs during installation is that the `graph` package (which `ggm` depends on) does not get installed from BioConductor automatically.

A possible solution is to add `biocViews:` to the DESCRIPTION file, as e.g. discussed here:

https://bioinformatics.stackexchange.com/questions/3365/r-package-development-how-does-one-automatically-install-bioconductor-packages

https://github.com/r-lib/devtools/issues/700

Would that be possible?

Thanks for your time,
Wouter.

**Comment by StaThin** [comment]
Hi Wouter!

I had some complaints like yours, and I suggested to install `graph`
from Bioconductor as usual, i.e.,  with

if (!require("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("graph")

In all cases the users forgot to do this before.

I didn't know the trick that you mention using by adding
biocViews: to the DESCRIPTION file. This appears to be
undocumented anywhere.

I can try to try this trick if you wish, even if biocViews is not at all
related to my package.
But you should  check please if it is automatically installed
only  the Bioconductor package `graph`.

What do you think?

Best wishes

Giovanni

**Comment by Ax3man** [comment]
Hi Giovanni,

Yes, it is as simple as installing `graph` from Bioconductor, but for users of `phylopath` this isn't always easy to see, since `graph` is not listed as a dependency, only `ggm` is.

I did some further digging and testing, and the `biocViews:` trick appears to only work when installing using e.g. `remotes::install_github()`, but doesn't appear to affect CRAN installs using `install.packages()`. I can confirm it will only install `graph` (not other Bioconductor packages).

So including the trick may help a bit, but not as much as I though.
